// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, first_name, last_name, password_hash, salt FROM account WHERE email = $1 LIMIT 1
`

type GetAccountByEmailRow struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	PasswordHash string
	Salt         string
}

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Salt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO account (first_name, last_name, email, password_hash, salt) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type InsertAccountParams struct {
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	Salt         string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
