// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT
    a.id,
    a.first_name,
    a.last_name,
    a.password_hash,
    a.email,
    CASE
        WHEN ad.account_id IS NOT NULL THEN 'admin'
        WHEN f.account_id IS NOT NULL THEN 'farmer'
        WHEN c.account_id IS NOT NULL THEN 'customer'
        ELSE ''
    END AS role
FROM account a
LEFT JOIN admin ad ON ad.account_id = a.id
LEFT JOIN farmer f ON f.account_id = a.id
LEFT JOIN customer c ON c.account_id = a.id
WHERE a.email = $1
LIMIT 1
`

type GetAccountByEmailRow struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	PasswordHash string
	Email        string
	Role         string
}

// Role is not stored on account; it is implied by which subtype table the
// account joins to. admin.role is an admin-internal tier, not the account role.
func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (GetAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i GetAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
    a.id,
    a.first_name,
    a.last_name,
    a.email,
    CASE
        WHEN ad.account_id IS NOT NULL THEN 'admin'
        WHEN f.account_id IS NOT NULL THEN 'farmer'
        WHEN c.account_id IS NOT NULL THEN 'customer'
        ELSE ''
    END AS role
FROM account a
LEFT JOIN admin ad ON ad.account_id = a.id
LEFT JOIN farmer f ON f.account_id = a.id
LEFT JOIN customer c ON c.account_id = a.id
WHERE a.id = $1
LIMIT 1
`

type GetAccountByIDRow struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Role      string
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO account (first_name, last_name, email, password_hash) VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertAccountParams struct {
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCustomer = `-- name: InsertCustomer :exec
INSERT INTO customer (account_id, postal_code) VALUES ($1, $2)
`

type InsertCustomerParams struct {
	AccountID  uuid.UUID
	PostalCode int32
}

// Links an account to the customer subtype table.
func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) error {
	_, err := q.db.Exec(ctx, insertCustomer, arg.AccountID, arg.PostalCode)
	return err
}

const insertFarmer = `-- name: InsertFarmer :exec
INSERT INTO farmer (account_id, farm_name, postal_code) VALUES ($1, $2, $3)
`

type InsertFarmerParams struct {
	AccountID  uuid.UUID
	FarmName   string
	PostalCode int32
}

// Links an account to the farmer subtype table. The account's role is derived
// from this membership; see GetAccountByEmail.
func (q *Queries) InsertFarmer(ctx context.Context, arg InsertFarmerParams) error {
	_, err := q.db.Exec(ctx, insertFarmer, arg.AccountID, arg.FarmName, arg.PostalCode)
	return err
}
