// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcement.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAnnouncementsByFarmer = `-- name: GetAnnouncementsByFarmer :many
SELECT a.id, a.farmer, a.subject, a.body, a.created_at, farm.name AS farm_name
FROM announcement a
JOIN farm ON farm.farmer_id = a.farmer
WHERE a.farmer = $1
ORDER BY a.created_at DESC
`

type GetAnnouncementsByFarmerRow struct {
	ID        uuid.UUID
	Farmer    uuid.UUID
	Subject   string
	Body      string
	CreatedAt pgtype.Timestamptz
	FarmName  string
}

// The farmer's own board: what he has posted, newest first.
func (q *Queries) GetAnnouncementsByFarmer(ctx context.Context, farmer uuid.UUID) ([]GetAnnouncementsByFarmerRow, error) {
	rows, err := q.db.Query(ctx, getAnnouncementsByFarmer, farmer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnnouncementsByFarmerRow
	for rows.Next() {
		var i GetAnnouncementsByFarmerRow
		if err := rows.Scan(
			&i.ID,
			&i.Farmer,
			&i.Subject,
			&i.Body,
			&i.CreatedAt,
			&i.FarmName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnnouncementsForCustomer = `-- name: GetAnnouncementsForCustomer :many
SELECT DISTINCT a.id, a.farmer, a.subject, a.body, a.created_at, farm.name AS farm_name
FROM announcement a
JOIN farm ON farm.farmer_id = a.farmer
JOIN field fi ON fi.farm = farm.id
JOIN plot p ON p.field = fi.id
JOIN rental r ON r.plot = p.id
WHERE r.customer = $1 AND r.period @> CURRENT_TIMESTAMP AND r.status = 'approved'
ORDER BY a.created_at DESC
`

type GetAnnouncementsForCustomerRow struct {
	ID        uuid.UUID
	Farmer    uuid.UUID
	Subject   string
	Body      string
	CreatedAt pgtype.Timestamptz
	FarmName  string
}

// The customer's board: notices from every farmer he is currently renting
// from. The rental gates which *farmers* he reads, not which notices, so the
// board is deliberately not a record of what he was mailed: a new renter reads
// everything that farmer has ever posted, including notices from before his
// rental began, and an ended rental takes the whole board with it. Renting
// several plots from the same farmer must not repeat that farmer's notices,
// hence DISTINCT.
func (q *Queries) GetAnnouncementsForCustomer(ctx context.Context, customer uuid.UUID) ([]GetAnnouncementsForCustomerRow, error) {
	rows, err := q.db.Query(ctx, getAnnouncementsForCustomer, customer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnnouncementsForCustomerRow
	for rows.Next() {
		var i GetAnnouncementsForCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Farmer,
			&i.Subject,
			&i.Body,
			&i.CreatedAt,
			&i.FarmName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomersOfFarmer = `-- name: GetCustomersOfFarmer :many
SELECT DISTINCT a.id, a.email, a.first_name, a.last_name
FROM account a
JOIN customer c ON c.account_id = a.id
JOIN rental r ON r.customer = c.account_id
JOIN plot p ON p.id = r.plot
JOIN field f ON f.id = p.field
JOIN farm ON farm.id = f.farm
WHERE farm.farmer_id = $1 AND r.period @> CURRENT_TIMESTAMP AND r.status = 'approved'
ORDER BY a.email
`

type GetCustomersOfFarmerRow struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
}

// Everyone a farmer may address: the customers currently renting one of his
// plots. DISTINCT is load-bearing — a customer renting three plots from the
// same farmer is one person and must be mailed once.
func (q *Queries) GetCustomersOfFarmer(ctx context.Context, farmerID uuid.UUID) ([]GetCustomersOfFarmerRow, error) {
	rows, err := q.db.Query(ctx, getCustomersOfFarmer, farmerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersOfFarmerRow
	for rows.Next() {
		var i GetCustomersOfFarmerRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAnnouncement = `-- name: InsertAnnouncement :one
WITH inserted AS (
    INSERT INTO announcement (farmer, subject, body)
    VALUES ($1, $2, $3)
    RETURNING id, farmer, subject, body, created_at
)
SELECT i.id, i.farmer, i.subject, i.body, i.created_at, farm.name AS farm_name
FROM inserted i
JOIN farm ON farm.farmer_id = i.farmer
`

type InsertAnnouncementParams struct {
	Farmer  uuid.UUID
	Subject string
	Body    string
}

type InsertAnnouncementRow struct {
	ID        uuid.UUID
	Farmer    uuid.UUID
	Subject   string
	Body      string
	CreatedAt pgtype.Timestamptz
	FarmName  string
}

// The farm name is joined back in so a stored announcement is immediately
// returnable in the same shape the board reads, without a second round trip.
func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (InsertAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement, arg.Farmer, arg.Subject, arg.Body)
	var i InsertAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
		&i.FarmName,
	)
	return i, err
}
