// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: broadcast_notification.sql

package database

import (
	"context"
)

const getAllBroadcastNotifications = `-- name: GetAllBroadcastNotifications :many
SELECT id, subject, body, created_at
FROM broadcast_notification
ORDER BY created_at DESC
`

func (q *Queries) GetAllBroadcastNotifications(ctx context.Context) ([]BroadcastNotification, error) {
	rows, err := q.db.Query(ctx, getAllBroadcastNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastNotification
	for rows.Next() {
		var i BroadcastNotification
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBroadcastNotification = `-- name: InsertBroadcastNotification :one
INSERT INTO broadcast_notification (subject, body)
VALUES ($1, $2)
RETURNING id, subject, body, created_at
`

type InsertBroadcastNotificationParams struct {
	Subject string
	Body    string
}

func (q *Queries) InsertBroadcastNotification(ctx context.Context, arg InsertBroadcastNotificationParams) (BroadcastNotification, error) {
	row := q.db.QueryRow(ctx, insertBroadcastNotification, arg.Subject, arg.Body)
	var i BroadcastNotification
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
