// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: care_instruction.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteCareInstruction = `-- name: DeleteCareInstruction :execrows
DELETE FROM care_instruction WHERE id = $1
`

// :execrows, unlike DeleteCrop's :exec, so the repository can tell "deleted"
// from "there was nothing with that id" and answer 404 rather than 204.
func (q *Queries) DeleteCareInstruction(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCareInstruction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCareInstructionsByCrop = `-- name: GetCareInstructionsByCrop :many
SELECT id, crop, week, title, body, created_at, updated_at
FROM care_instruction
WHERE crop = $1
ORDER BY week, created_at
`

func (q *Queries) GetCareInstructionsByCrop(ctx context.Context, crop uuid.UUID) ([]CareInstruction, error) {
	rows, err := q.db.Query(ctx, getCareInstructionsByCrop, crop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareInstruction
	for rows.Next() {
		var i CareInstruction
		if err := rows.Scan(
			&i.ID,
			&i.Crop,
			&i.Week,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCareInstructionsByCrops = `-- name: GetCareInstructionsByCrops :many
SELECT id, crop, week, title, body, created_at, updated_at
FROM care_instruction
WHERE crop = ANY($1::uuid[])
ORDER BY week, created_at
`

// The customer-facing read: one round trip for every crop the customer is
// currently growing, grouped by crop in the repository. Several instructions
// may share a week (a week is a list of tasks, not one task), so created_at
// breaks the tie and keeps the order an admin entered them in.
func (q *Queries) GetCareInstructionsByCrops(ctx context.Context, crops []uuid.UUID) ([]CareInstruction, error) {
	rows, err := q.db.Query(ctx, getCareInstructionsByCrops, crops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareInstruction
	for rows.Next() {
		var i CareInstruction
		if err := rows.Scan(
			&i.ID,
			&i.Crop,
			&i.Week,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCareInstruction = `-- name: InsertCareInstruction :one
INSERT INTO care_instruction (crop, week, title, body)
VALUES ($1, $2, $3, $4)
RETURNING id, crop, week, title, body, created_at, updated_at
`

type InsertCareInstructionParams struct {
	Crop  uuid.UUID
	Week  int32
	Title string
	Body  string
}

func (q *Queries) InsertCareInstruction(ctx context.Context, arg InsertCareInstructionParams) (CareInstruction, error) {
	row := q.db.QueryRow(ctx, insertCareInstruction,
		arg.Crop,
		arg.Week,
		arg.Title,
		arg.Body,
	)
	var i CareInstruction
	err := row.Scan(
		&i.ID,
		&i.Crop,
		&i.Week,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCareInstruction = `-- name: UpdateCareInstruction :one
UPDATE care_instruction
SET week = $2, title = $3, body = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, crop, week, title, body, created_at, updated_at
`

type UpdateCareInstructionParams struct {
	ID    uuid.UUID
	Week  int32
	Title string
	Body  string
}

// Edits every field but the crop: moving an instruction to another crop is a
// different guide, not an edit, so it is a delete plus an insert.
func (q *Queries) UpdateCareInstruction(ctx context.Context, arg UpdateCareInstructionParams) (CareInstruction, error) {
	row := q.db.QueryRow(ctx, updateCareInstruction,
		arg.ID,
		arg.Week,
		arg.Title,
		arg.Body,
	)
	var i CareInstruction
	err := row.Scan(
		&i.ID,
		&i.Crop,
		&i.Week,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
