// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crop.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFieldCrops = `-- name: DeleteFieldCrops :exec
DELETE FROM field_crop WHERE field = $1
`

func (q *Queries) DeleteFieldCrops(ctx context.Context, field uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFieldCrops, field)
	return err
}

const getAllCrops = `-- name: GetAllCrops :many
SELECT id, name, duration_months
FROM crop
ORDER BY name
`

func (q *Queries) GetAllCrops(ctx context.Context) ([]Crop, error) {
	rows, err := q.db.Query(ctx, getAllCrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crop
	for rows.Next() {
		var i Crop
		if err := rows.Scan(&i.ID, &i.Name, &i.DurationMonths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropByID = `-- name: GetCropByID :one
SELECT id, name, duration_months
FROM crop
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCropByID(ctx context.Context, id uuid.UUID) (Crop, error) {
	row := q.db.QueryRow(ctx, getCropByID, id)
	var i Crop
	err := row.Scan(&i.ID, &i.Name, &i.DurationMonths)
	return i, err
}

const getCropsByField = `-- name: GetCropsByField :many
SELECT c.id, c.name, c.duration_months
FROM field_crop fc
JOIN crop c ON c.id = fc.crop
WHERE fc.field = $1
ORDER BY c.name
`

func (q *Queries) GetCropsByField(ctx context.Context, field uuid.UUID) ([]Crop, error) {
	rows, err := q.db.Query(ctx, getCropsByField, field)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crop
	for rows.Next() {
		var i Crop
		if err := rows.Scan(&i.ID, &i.Name, &i.DurationMonths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropsByFields = `-- name: GetCropsByFields :many
SELECT fc.field, c.id, c.name, c.duration_months
FROM field_crop fc
JOIN crop c ON c.id = fc.crop
WHERE fc.field = ANY($1::uuid[])
ORDER BY c.name
`

type GetCropsByFieldsRow struct {
	Field          uuid.UUID
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

func (q *Queries) GetCropsByFields(ctx context.Context, fields []uuid.UUID) ([]GetCropsByFieldsRow, error) {
	rows, err := q.db.Query(ctx, getCropsByFields, fields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCropsByFieldsRow
	for rows.Next() {
		var i GetCropsByFieldsRow
		if err := rows.Scan(
			&i.Field,
			&i.ID,
			&i.Name,
			&i.DurationMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCrop = `-- name: InsertCrop :one
INSERT INTO crop (name, duration_months) VALUES ($1, $2) RETURNING id
`

type InsertCropParams struct {
	Name           string
	DurationMonths int32
}

func (q *Queries) InsertCrop(ctx context.Context, arg InsertCropParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCrop, arg.Name, arg.DurationMonths)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertFieldCrop = `-- name: InsertFieldCrop :exec
INSERT INTO field_crop (field, crop) VALUES ($1, $2)
`

type InsertFieldCropParams struct {
	Field uuid.UUID
	Crop  uuid.UUID
}

func (q *Queries) InsertFieldCrop(ctx context.Context, arg InsertFieldCropParams) error {
	_, err := q.db.Exec(ctx, insertFieldCrop, arg.Field, arg.Crop)
	return err
}
