// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crop.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteCrop = `-- name: DeleteCrop :exec
DELETE FROM crop WHERE id = $1
`

func (q *Queries) DeleteCrop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCrop, id)
	return err
}

const deletePlotCrops = `-- name: DeletePlotCrops :exec
DELETE FROM plot_crop WHERE plot = $1
`

func (q *Queries) DeletePlotCrops(ctx context.Context, plot uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlotCrops, plot)
	return err
}

const getAllCrops = `-- name: GetAllCrops :many
SELECT id, name, duration_months
FROM crop
WHERE NOT is_placeholder
ORDER BY name
`

type GetAllCropsRow struct {
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

func (q *Queries) GetAllCrops(ctx context.Context) ([]GetAllCropsRow, error) {
	rows, err := q.db.Query(ctx, getAllCrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCropsRow
	for rows.Next() {
		var i GetAllCropsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DurationMonths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropByID = `-- name: GetCropByID :one
SELECT id, name, duration_months
FROM crop
WHERE id = $1
LIMIT 1
`

type GetCropByIDRow struct {
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

func (q *Queries) GetCropByID(ctx context.Context, id uuid.UUID) (GetCropByIDRow, error) {
	row := q.db.QueryRow(ctx, getCropByID, id)
	var i GetCropByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.DurationMonths)
	return i, err
}

const getCropsByPlot = `-- name: GetCropsByPlot :many
SELECT c.id, c.name, c.duration_months
FROM plot_crop pc
JOIN crop c ON c.id = pc.crop
WHERE pc.plot = $1
ORDER BY c.name
`

type GetCropsByPlotRow struct {
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

func (q *Queries) GetCropsByPlot(ctx context.Context, plot uuid.UUID) ([]GetCropsByPlotRow, error) {
	rows, err := q.db.Query(ctx, getCropsByPlot, plot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCropsByPlotRow
	for rows.Next() {
		var i GetCropsByPlotRow
		if err := rows.Scan(&i.ID, &i.Name, &i.DurationMonths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropsByPlots = `-- name: GetCropsByPlots :many
SELECT pc.plot, c.id, c.name, c.duration_months
FROM plot_crop pc
JOIN crop c ON c.id = pc.crop
WHERE pc.plot = ANY($1::uuid[])
ORDER BY c.name
`

type GetCropsByPlotsRow struct {
	Plot           uuid.UUID
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

func (q *Queries) GetCropsByPlots(ctx context.Context, plots []uuid.UUID) ([]GetCropsByPlotsRow, error) {
	rows, err := q.db.Query(ctx, getCropsByPlots, plots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCropsByPlotsRow
	for rows.Next() {
		var i GetCropsByPlotsRow
		if err := rows.Scan(
			&i.Plot,
			&i.ID,
			&i.Name,
			&i.DurationMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCrop = `-- name: InsertCrop :one
INSERT INTO crop (name, duration_months) VALUES ($1, $2) RETURNING id
`

type InsertCropParams struct {
	Name           string
	DurationMonths int32
}

func (q *Queries) InsertCrop(ctx context.Context, arg InsertCropParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCrop, arg.Name, arg.DurationMonths)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPlotCrop = `-- name: InsertPlotCrop :exec
INSERT INTO plot_crop (plot, crop) VALUES ($1, $2)
`

type InsertPlotCropParams struct {
	Plot uuid.UUID
	Crop uuid.UUID
}

func (q *Queries) InsertPlotCrop(ctx context.Context, arg InsertPlotCropParams) error {
	_, err := q.db.Exec(ctx, insertPlotCrop, arg.Plot, arg.Crop)
	return err
}
