// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crop.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCrop = `-- name: DeleteCrop :exec
DELETE FROM crop WHERE id = $1
`

func (q *Queries) DeleteCrop(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCrop, id)
	return err
}

const deletePlotCrops = `-- name: DeletePlotCrops :exec
DELETE FROM plot_crop WHERE plot = $1
`

func (q *Queries) DeletePlotCrops(ctx context.Context, plot uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlotCrops, plot)
	return err
}

const getAllCrops = `-- name: GetAllCrops :many
SELECT id, name, duration_months
FROM crop
ORDER BY name
`

func (q *Queries) GetAllCrops(ctx context.Context) ([]Crop, error) {
	rows, err := q.db.Query(ctx, getAllCrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crop
	for rows.Next() {
		var i Crop
		if err := rows.Scan(&i.ID, &i.Name, &i.DurationMonths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropByID = `-- name: GetCropByID :one
SELECT id, name, duration_months
FROM crop
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCropByID(ctx context.Context, id uuid.UUID) (Crop, error) {
	row := q.db.QueryRow(ctx, getCropByID, id)
	var i Crop
	err := row.Scan(&i.ID, &i.Name, &i.DurationMonths)
	return i, err
}

const getCropsByPlot = `-- name: GetCropsByPlot :many
SELECT c.id, c.name, c.duration_months
FROM plot_crop pc
JOIN crop c ON c.id = pc.crop
WHERE pc.plot = $1
ORDER BY c.name
`

func (q *Queries) GetCropsByPlot(ctx context.Context, plot uuid.UUID) ([]Crop, error) {
	rows, err := q.db.Query(ctx, getCropsByPlot, plot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crop
	for rows.Next() {
		var i Crop
		if err := rows.Scan(&i.ID, &i.Name, &i.DurationMonths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCropsByPlots = `-- name: GetCropsByPlots :many
SELECT pc.plot, c.id, c.name, c.duration_months
FROM plot_crop pc
JOIN crop c ON c.id = pc.crop
WHERE pc.plot = ANY($1::uuid[])
ORDER BY c.name
`

type GetCropsByPlotsRow struct {
	Plot           uuid.UUID
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

func (q *Queries) GetCropsByPlots(ctx context.Context, plots []uuid.UUID) ([]GetCropsByPlotsRow, error) {
	rows, err := q.db.Query(ctx, getCropsByPlots, plots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCropsByPlotsRow
	for rows.Next() {
		var i GetCropsByPlotsRow
		if err := rows.Scan(
			&i.Plot,
			&i.ID,
			&i.Name,
			&i.DurationMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPricedCropOfferingsByPlots = `-- name: GetPricedCropOfferingsByPlots :many
SELECT
    pc.plot,
    c.id, c.name, c.duration_months,
    p.base_price_cents_per_sqm_per_week,
    fcr.price_cents_per_sqm_per_week AS farm_crop_rate_cents_per_sqm_per_week,
    ST_Area(p.coordinates::geography)::float8 AS area_square_meters
FROM plot_crop pc
JOIN plot p ON p.id = pc.plot
JOIN crop c ON c.id = pc.crop
JOIN field f ON f.id = p.field
JOIN farm_crop_rate fcr ON fcr.farm = f.farm AND fcr.crop = pc.crop
WHERE pc.plot = ANY($1::uuid[])
  AND p.base_price_cents_per_sqm_per_week IS NOT NULL
ORDER BY c.name
`

type GetPricedCropOfferingsByPlotsRow struct {
	Plot                           uuid.UUID
	ID                             uuid.UUID
	Name                           string
	DurationMonths                 int32
	BasePriceCentsPerSqmPerWeek    pgtype.Int4
	FarmCropRateCentsPerSqmPerWeek int32
	AreaSquareMeters               float64
}

// Only rows where both halves of the price are set: the plot's own base
// rate, and the farm's rate for that crop. A crop missing either is not a
// real offer from a customer's perspective (see PlotSearchService), so it
// must not appear in the results at all -- not with a null or zero price.
func (q *Queries) GetPricedCropOfferingsByPlots(ctx context.Context, plots []uuid.UUID) ([]GetPricedCropOfferingsByPlotsRow, error) {
	rows, err := q.db.Query(ctx, getPricedCropOfferingsByPlots, plots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPricedCropOfferingsByPlotsRow
	for rows.Next() {
		var i GetPricedCropOfferingsByPlotsRow
		if err := rows.Scan(
			&i.Plot,
			&i.ID,
			&i.Name,
			&i.DurationMonths,
			&i.BasePriceCentsPerSqmPerWeek,
			&i.FarmCropRateCentsPerSqmPerWeek,
			&i.AreaSquareMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCrop = `-- name: InsertCrop :one
INSERT INTO crop (name, duration_months) VALUES ($1, $2) RETURNING id
`

type InsertCropParams struct {
	Name           string
	DurationMonths int32
}

func (q *Queries) InsertCrop(ctx context.Context, arg InsertCropParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCrop, arg.Name, arg.DurationMonths)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPlotCrop = `-- name: InsertPlotCrop :exec
INSERT INTO plot_crop (plot, crop) VALUES ($1, $2)
`

type InsertPlotCropParams struct {
	Plot uuid.UUID
	Crop uuid.UUID
}

func (q *Queries) InsertPlotCrop(ctx context.Context, arg InsertPlotCropParams) error {
	_, err := q.db.Exec(ctx, insertPlotCrop, arg.Plot, arg.Crop)
	return err
}
