// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_notification_preferences.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCustomerNotificationPreferences = `-- name: GetCustomerNotificationPreferences :one
SELECT notify_messages_by_email
FROM customer
WHERE account_id = $1
`

func (q *Queries) GetCustomerNotificationPreferences(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getCustomerNotificationPreferences, accountID)
	var notify_messages_by_email bool
	err := row.Scan(&notify_messages_by_email)
	return notify_messages_by_email, err
}

const updateCustomerNotificationPreferences = `-- name: UpdateCustomerNotificationPreferences :execrows
UPDATE customer
SET notify_messages_by_email = $2
WHERE account_id = $1
`

type UpdateCustomerNotificationPreferencesParams struct {
	AccountID             uuid.UUID
	NotifyMessagesByEmail bool
}

func (q *Queries) UpdateCustomerNotificationPreferences(ctx context.Context, arg UpdateCustomerNotificationPreferencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCustomerNotificationPreferences, arg.AccountID, arg.NotifyMessagesByEmail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
