// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: farm.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFarmByID = `-- name: GetFarmByID :one
SELECT
    farm.id,
    farm.farmer_id,
    farm.name,
    farm.address,
    farm.description,
    farm.founded_at,
    COALESCE(SUM(ST_Area(p.coordinates::geography)), 0)::float8 AS total_square_meters
FROM farm
LEFT JOIN field fi ON fi.farm = farm.id
LEFT JOIN plot p ON p.field = fi.id
WHERE farm.id = $1
GROUP BY farm.id
`

type GetFarmByIDRow struct {
	ID                uuid.UUID
	FarmerID          uuid.UUID
	Name              string
	Address           string
	Description       string
	FoundedAt         pgtype.Date
	TotalSquareMeters float64
}

// TotalSquareMeters sums every plot across every field of this farm; a farm
// with no fields or plots gets 0, not an error.
func (q *Queries) GetFarmByID(ctx context.Context, id uuid.UUID) (GetFarmByIDRow, error) {
	row := q.db.QueryRow(ctx, getFarmByID, id)
	var i GetFarmByIDRow
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.FoundedAt,
		&i.TotalSquareMeters,
	)
	return i, err
}

const getFarmIDByFarmerID = `-- name: GetFarmIDByFarmerID :one
SELECT id FROM farm WHERE farmer_id = $1
`

// Lean lookup for ownership checks: resolves a farmer's own farm id without
// the area-summing join GetFarmByID does.
func (q *Queries) GetFarmIDByFarmerID(ctx context.Context, farmerID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFarmIDByFarmerID, farmerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertFarm = `-- name: InsertFarm :one
INSERT INTO farm (farmer_id, name, address, description) VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertFarmParams struct {
	FarmerID    uuid.UUID
	Name        string
	Address     string
	Description string
}

func (q *Queries) InsertFarm(ctx context.Context, arg InsertFarmParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertFarm,
		arg.FarmerID,
		arg.Name,
		arg.Address,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listFarms = `-- name: ListFarms :many
WITH listed AS (
    SELECT
        farm.id,
        farm.farmer_id,
        farm.name,
        farm.address,
        fr.postal_code,
        a.first_name,
        a.last_name,
        a.email,
        a.created_at,
        COALESCE(farm_fields.total, 0)::bigint   AS field_count,
        COALESCE(farm_fields.area, 0)::float8    AS field_area_square_meters,
        COALESCE(farm_plots.total, 0)::bigint    AS plot_count,
        COALESCE(farm_plots.rented, 0)::bigint   AS rented_plot_count,
        COALESCE(farm_plots.area, 0)::float8     AS plot_area_square_meters,
        COALESCE(farm_rentals.active, 0)::bigint AS active_rental_count
    FROM farm
    JOIN farmer fr ON fr.account_id = farm.farmer_id
    JOIN account a ON a.id = farm.farmer_id
    LEFT JOIN LATERAL (
        SELECT
            COUNT(*)::bigint AS total,
            COALESCE(SUM(ST_Area(coordinates::geography)::float8), 0)::float8 AS area
        FROM field
        WHERE field.farm = farm.id
    ) farm_fields ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            COUNT(*)::bigint AS total,
            (COUNT(*) FILTER (
                WHERE EXISTS (
                    SELECT 1 FROM rental r
                    WHERE r.plot = p.id AND r.period @> CURRENT_TIMESTAMP AND r.status = 'approved'
                )
            ))::bigint AS rented,
            COALESCE(SUM(ST_Area(p.coordinates::geography)::float8), 0)::float8 AS area
        FROM plot p
        JOIN field pf ON pf.id = p.field
        WHERE pf.farm = farm.id
    ) farm_plots ON TRUE
    LEFT JOIN LATERAL (
        SELECT (COUNT(*) FILTER (WHERE r.period @> CURRENT_TIMESTAMP AND r.status = 'approved'))::bigint AS active
        FROM rental r
        JOIN plot rp ON rp.id = r.plot
        JOIN field rf ON rf.id = rp.field
        WHERE rf.farm = farm.id
    ) farm_rentals ON TRUE
)
SELECT
    listed.id,
    listed.farmer_id,
    listed.name,
    listed.address,
    listed.postal_code,
    listed.first_name,
    listed.last_name,
    listed.email,
    listed.created_at,
    listed.field_count,
    listed.field_area_square_meters,
    listed.plot_count,
    listed.rented_plot_count,
    listed.plot_area_square_meters,
    listed.active_rental_count,
    (COUNT(*) OVER ())::bigint AS total_count
FROM listed
WHERE (
        $1::text = ''
        OR listed.name ILIKE '%' || $1::text || '%'
        OR listed.address ILIKE '%' || $1::text || '%'
        OR listed.email ILIKE '%' || $1::text || '%'
        OR listed.first_name ILIKE '%' || $1::text || '%'
        OR listed.last_name ILIKE '%' || $1::text || '%'
    )
  AND ($2::int IS NULL OR listed.postal_code = $2::int)
ORDER BY listed.name, listed.id
LIMIT $4 OFFSET $3
`

type ListFarmsParams struct {
	Search       string
	PostalCode   pgtype.Int4
	ResultOffset int32
	ResultLimit  int32
}

type ListFarmsRow struct {
	ID                    uuid.UUID
	FarmerID              uuid.UUID
	Name                  string
	Address               string
	PostalCode            int32
	FirstName             string
	LastName              string
	Email                 string
	CreatedAt             pgtype.Timestamptz
	FieldCount            int64
	FieldAreaSquareMeters float64
	PlotCount             int64
	RentedPlotCount       int64
	PlotAreaSquareMeters  float64
	ActiveRentalCount     int64
	TotalCount            int64
}

// One page of the admin farm list.
//
// The per-farm figures are computed with exactly the predicates
// statistics.sql uses -- same ST_Area over ::geography, same
// "period @> CURRENT_TIMESTAMP" test for rented right now. That is what makes
// these rows reconcile with GetPlatformStatistics: summing field_count,
// plot_count and rented_plot_count across every row of this list reproduces
// the platform figures exactly. Change a predicate in one place and the two
// admin screens start disagreeing.
//
// Each aggregate hangs off its own LATERAL join rather than a GROUP BY over a
// join of all three: grouping a farm's fields, plots and rentals in one pass
// would multiply the rows against each other and count each field once per
// plot. GetFarmByID can group, because it aggregates one thing for one farm.
//
// An ungrouped aggregate returns one row even over no rows at all, so a farm
// with nothing is a row of zeros rather than a missing row -- the same promise
// GetFarmStatistics makes to a farm that owns nothing. The COALESCEs restate
// that for sqlc, which types a LEFT JOIN's columns as nullable regardless.
//
// total_count is how many rows match the filter before LIMIT, taken in the same
// query so the count and the page come from one snapshot. A page past the end
// returns no rows, and therefore no count either.
// An empty search and a NULL postal code each mean "no filter", so one query
// serves every combination of them.
// Farm names are not unique, so id breaks the tie and keeps paging stable.
func (q *Queries) ListFarms(ctx context.Context, arg ListFarmsParams) ([]ListFarmsRow, error) {
	rows, err := q.db.Query(ctx, listFarms,
		arg.Search,
		arg.PostalCode,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFarmsRow
	for rows.Next() {
		var i ListFarmsRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmerID,
			&i.Name,
			&i.Address,
			&i.PostalCode,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CreatedAt,
			&i.FieldCount,
			&i.FieldAreaSquareMeters,
			&i.PlotCount,
			&i.RentedPlotCount,
			&i.PlotAreaSquareMeters,
			&i.ActiveRentalCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
