// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farm_crop_rate.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFarmCropRates = `-- name: DeleteFarmCropRates :exec
DELETE FROM farm_crop_rate WHERE farm = $1
`

func (q *Queries) DeleteFarmCropRates(ctx context.Context, farm uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFarmCropRates, farm)
	return err
}

const getFarmCropRate = `-- name: GetFarmCropRate :one
SELECT price_cents_per_sqm_per_week
FROM farm_crop_rate
WHERE farm = $1 AND crop = $2
LIMIT 1
`

type GetFarmCropRateParams struct {
	Farm uuid.UUID
	Crop uuid.UUID
}

func (q *Queries) GetFarmCropRate(ctx context.Context, arg GetFarmCropRateParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFarmCropRate, arg.Farm, arg.Crop)
	var price_cents_per_sqm_per_week int32
	err := row.Scan(&price_cents_per_sqm_per_week)
	return price_cents_per_sqm_per_week, err
}

const getFarmCropRates = `-- name: GetFarmCropRates :many
SELECT crop, price_cents_per_sqm_per_week
FROM farm_crop_rate
WHERE farm = $1
ORDER BY crop
`

type GetFarmCropRatesRow struct {
	Crop                    uuid.UUID
	PriceCentsPerSqmPerWeek int32
}

func (q *Queries) GetFarmCropRates(ctx context.Context, farm uuid.UUID) ([]GetFarmCropRatesRow, error) {
	rows, err := q.db.Query(ctx, getFarmCropRates, farm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFarmCropRatesRow
	for rows.Next() {
		var i GetFarmCropRatesRow
		if err := rows.Scan(&i.Crop, &i.PriceCentsPerSqmPerWeek); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFarmCropRate = `-- name: InsertFarmCropRate :exec
INSERT INTO farm_crop_rate (farm, crop, price_cents_per_sqm_per_week)
VALUES ($1, $2, $3)
`

type InsertFarmCropRateParams struct {
	Farm                    uuid.UUID
	Crop                    uuid.UUID
	PriceCentsPerSqmPerWeek int32
}

func (q *Queries) InsertFarmCropRate(ctx context.Context, arg InsertFarmCropRateParams) error {
	_, err := q.db.Exec(ctx, insertFarmCropRate, arg.Farm, arg.Crop, arg.PriceCentsPerSqmPerWeek)
	return err
}
