// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farmer_subscription.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateFarmerSubscription = `-- name: ActivateFarmerSubscription :one
UPDATE farmer_subscription
SET status = 'active', stripe_subscription_id = $1, current_period_end = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND status = 'pending'
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

type ActivateFarmerSubscriptionParams struct {
	StripeSubscriptionID pgtype.Text
	CurrentPeriodEnd     pgtype.Timestamptz
	ID                   uuid.UUID
}

// The WHERE guard makes this idempotent-safe: Stripe retries webhook
// delivery, so a second checkout.session.completed for the same session
// must not re-run this.
func (q *Queries) ActivateFarmerSubscription(ctx context.Context, arg ActivateFarmerSubscriptionParams) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, activateFarmerSubscription, arg.StripeSubscriptionID, arg.CurrentPeriodEnd, arg.ID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelFarmerSubscription = `-- name: CancelFarmerSubscription :one
UPDATE farmer_subscription
SET status = 'canceled', updated_at = CURRENT_TIMESTAMP
WHERE stripe_subscription_id = $1 AND status IN ('pending', 'active', 'past_due')
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

// Fired by customer.subscription.deleted. Guarded against a subscription
// that is already canceled (e.g. a retried webhook delivery).
func (q *Queries) CancelFarmerSubscription(ctx context.Context, stripeSubscriptionID pgtype.Text) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, cancelFarmerSubscription, stripeSubscriptionID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireFarmerSubscription = `-- name: ExpireFarmerSubscription :one
UPDATE farmer_subscription
SET status = 'canceled', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

// Same idempotency guard as ActivateFarmerSubscription.
func (q *Queries) ExpireFarmerSubscription(ctx context.Context, id uuid.UUID) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, expireFarmerSubscription, id)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSubscriptionByFarmer = `-- name: GetActiveSubscriptionByFarmer :one
SELECT id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
FROM farmer_subscription
WHERE farmer = $1 AND status IN ('active', 'past_due')
LIMIT 1
`

// Used by the RequireActiveSubscription middleware and the plot-count cap
// check. Returns no rows (mapped to ErrNotFound) if the farmer has never
// subscribed, or their only subscription is pending/canceled.
func (q *Queries) GetActiveSubscriptionByFarmer(ctx context.Context, farmer uuid.UUID) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByFarmer, farmer)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFarmerSubscriptionBySessionID = `-- name: GetFarmerSubscriptionBySessionID :one
SELECT id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
FROM farmer_subscription
WHERE stripe_checkout_session_id = $1
LIMIT 1
`

func (q *Queries) GetFarmerSubscriptionBySessionID(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, getFarmerSubscriptionBySessionID, stripeCheckoutSessionID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFarmerSubscriptionByStripeSubscriptionID = `-- name: GetFarmerSubscriptionByStripeSubscriptionID :one
SELECT id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
FROM farmer_subscription
WHERE stripe_subscription_id = $1
LIMIT 1
`

func (q *Queries) GetFarmerSubscriptionByStripeSubscriptionID(ctx context.Context, stripeSubscriptionID pgtype.Text) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, getFarmerSubscriptionByStripeSubscriptionID, stripeSubscriptionID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByFarmer = `-- name: GetSubscriptionByFarmer :one
SELECT id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
FROM farmer_subscription
WHERE farmer = $1 AND status IN ('pending', 'active', 'past_due')
LIMIT 1
`

// Unlike GetActiveSubscriptionByFarmer, this returns the farmer's current
// non-terminal subscription regardless of status (including pending), so a
// farmer mid-checkout can poll their own status.
func (q *Queries) GetSubscriptionByFarmer(ctx context.Context, farmer uuid.UUID) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByFarmer, farmer)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFarmerSubscription = `-- name: InsertFarmerSubscription :one
INSERT INTO farmer_subscription (farmer, plan, stripe_customer_id, stripe_checkout_session_id)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

type InsertFarmerSubscriptionParams struct {
	Farmer                  uuid.UUID
	Plan                    uuid.UUID
	StripeCustomerID        string
	StripeCheckoutSessionID pgtype.Text
}

func (q *Queries) InsertFarmerSubscription(ctx context.Context, arg InsertFarmerSubscriptionParams) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, insertFarmerSubscription,
		arg.Farmer,
		arg.Plan,
		arg.StripeCustomerID,
		arg.StripeCheckoutSessionID,
	)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFarmerSubscriptionPastDue = `-- name: MarkFarmerSubscriptionPastDue :one
UPDATE farmer_subscription
SET status = 'past_due', updated_at = CURRENT_TIMESTAMP
WHERE stripe_subscription_id = $1 AND status = 'active'
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

// Keyed by Stripe subscription id, since invoice.payment_failed carries
// that rather than a checkout session id. Guarded to only affect a
// currently-active subscription.
func (q *Queries) MarkFarmerSubscriptionPastDue(ctx context.Context, stripeSubscriptionID pgtype.Text) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, markFarmerSubscriptionPastDue, stripeSubscriptionID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reactivateFarmerSubscription = `-- name: ReactivateFarmerSubscription :one
UPDATE farmer_subscription
SET status = 'active', current_period_end = $1, updated_at = CURRENT_TIMESTAMP
WHERE stripe_subscription_id = $2 AND status IN ('active', 'past_due')
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

type ReactivateFarmerSubscriptionParams struct {
	CurrentPeriodEnd     pgtype.Timestamptz
	StripeSubscriptionID pgtype.Text
}

// Fired by invoice.payment_succeeded: covers both a routine renewal (already
// active, this just refreshes current_period_end) and recovery from
// past_due, so it is not guarded on a specific prior status the way the
// other transitions are.
func (q *Queries) ReactivateFarmerSubscription(ctx context.Context, arg ReactivateFarmerSubscriptionParams) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, reactivateFarmerSubscription, arg.CurrentPeriodEnd, arg.StripeSubscriptionID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFarmerSubscriptionPlan = `-- name: UpdateFarmerSubscriptionPlan :one
UPDATE farmer_subscription
SET plan = $1, current_period_end = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND status IN ('active', 'past_due')
RETURNING id, farmer, plan, stripe_customer_id, stripe_subscription_id, stripe_checkout_session_id, status, current_period_end, created_at, updated_at
`

type UpdateFarmerSubscriptionPlanParams struct {
	Plan             uuid.UUID
	CurrentPeriodEnd pgtype.Timestamptz
	ID               uuid.UUID
}

// Fired by a farmer-initiated upgrade: repoints plan and refreshes
// current_period_end from Stripe's proration response. Guarded to only
// affect a subscription that is actually live (active or past_due) -- a
// pending/canceled one has no live Stripe subscription to modify.
func (q *Queries) UpdateFarmerSubscriptionPlan(ctx context.Context, arg UpdateFarmerSubscriptionPlanParams) (FarmerSubscription, error) {
	row := q.db.QueryRow(ctx, updateFarmerSubscriptionPlan, arg.Plan, arg.CurrentPeriodEnd, arg.ID)
	var i FarmerSubscription
	err := row.Scan(
		&i.ID,
		&i.Farmer,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
