// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farm.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFarmByID = `-- name: GetFarmByID :one
SELECT
    farm.id,
    farm.farmer_id,
    farm.name,
    farm.address,
    farm.description,
    farm.founded_at,
    COALESCE(SUM(ST_Area(p.coordinates::geography)), 0)::float8 AS total_square_meters
FROM farm
LEFT JOIN field fi ON fi.farm = farm.id
LEFT JOIN plot p ON p.field = fi.id
WHERE farm.id = $1
GROUP BY farm.id
`

type GetFarmByIDRow struct {
	ID                uuid.UUID
	FarmerID          uuid.UUID
	Name              string
	Address           string
	Description       string
	FoundedAt         pgtype.Date
	TotalSquareMeters float64
}

// TotalSquareMeters sums every plot across every field of this farm; a farm
// with no fields or plots gets 0, not an error.
func (q *Queries) GetFarmByID(ctx context.Context, id uuid.UUID) (GetFarmByIDRow, error) {
	row := q.db.QueryRow(ctx, getFarmByID, id)
	var i GetFarmByIDRow
	err := row.Scan(
		&i.ID,
		&i.FarmerID,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.FoundedAt,
		&i.TotalSquareMeters,
	)
	return i, err
}

const getFarmIDByFarmerID = `-- name: GetFarmIDByFarmerID :one
SELECT id FROM farm WHERE farmer_id = $1
`

// Lean lookup for ownership checks: resolves a farmer's own farm id without
// the area-summing join GetFarmByID does.
func (q *Queries) GetFarmIDByFarmerID(ctx context.Context, farmerID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFarmIDByFarmerID, farmerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertFarm = `-- name: InsertFarm :one
INSERT INTO farm (farmer_id, name, address, description) VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertFarmParams struct {
	FarmerID    uuid.UUID
	Name        string
	Address     string
	Description string
}

func (q *Queries) InsertFarm(ctx context.Context, arg InsertFarmParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertFarm,
		arg.FarmerID,
		arg.Name,
		arg.Address,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
