// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: farm.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listFarms = `-- name: ListFarms :many

WITH listed AS (
    SELECT
        a.id,
        a.first_name,
        a.last_name,
        a.email,
        a.created_at,
        f.farm_name,
        f.postal_code,
        COALESCE(farm_fields.total, 0)::bigint  AS field_count,
        COALESCE(farm_fields.area, 0)::float8   AS field_area_square_meters,
        COALESCE(farm_plots.total, 0)::bigint   AS plot_count,
        COALESCE(farm_plots.rented, 0)::bigint  AS rented_plot_count,
        COALESCE(farm_plots.area, 0)::float8    AS plot_area_square_meters,
        COALESCE(farm_rentals.active, 0)::bigint AS active_rental_count
    FROM farmer f
    JOIN account a ON a.id = f.account_id
    LEFT JOIN LATERAL (
        SELECT
            COUNT(*)::bigint AS total,
            COALESCE(SUM(ST_Area(coordinates::geography)::float8), 0)::float8 AS area
        FROM field
        WHERE field.farmer = f.account_id
    ) farm_fields ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            COUNT(*)::bigint AS total,
            (COUNT(*) FILTER (
                WHERE EXISTS (
                    SELECT 1 FROM rental r
                    WHERE r.plot = p.id AND r.period @> CURRENT_TIMESTAMP
                )
            ))::bigint AS rented,
            COALESCE(SUM(ST_Area(p.coordinates::geography)::float8), 0)::float8 AS area
        FROM plot p
        JOIN field pf ON pf.id = p.field
        WHERE pf.farmer = f.account_id
    ) farm_plots ON TRUE
    LEFT JOIN LATERAL (
        SELECT (COUNT(*) FILTER (WHERE r.period @> CURRENT_TIMESTAMP))::bigint AS active
        FROM rental r
        JOIN plot rp ON rp.id = r.plot
        JOIN field rf ON rf.id = rp.field
        WHERE rf.farmer = f.account_id
    ) farm_rentals ON TRUE
)
SELECT
    listed.id,
    listed.first_name,
    listed.last_name,
    listed.email,
    listed.created_at,
    listed.farm_name,
    listed.postal_code,
    listed.field_count,
    listed.field_area_square_meters,
    listed.plot_count,
    listed.rented_plot_count,
    listed.plot_area_square_meters,
    listed.active_rental_count,
    (COUNT(*) OVER ())::bigint AS total_count
FROM listed
WHERE (
        $1::text = ''
        OR listed.farm_name ILIKE '%' || $1::text || '%'
        OR listed.email ILIKE '%' || $1::text || '%'
        OR listed.first_name ILIKE '%' || $1::text || '%'
        OR listed.last_name ILIKE '%' || $1::text || '%'
    )
  AND ($2::int IS NULL OR listed.postal_code = $2::int)
ORDER BY listed.farm_name, listed.id
LIMIT $4 OFFSET $3
`

type ListFarmsParams struct {
	Search       string
	PostalCode   pgtype.Int4
	ResultOffset int32
	ResultLimit  int32
}

type ListFarmsRow struct {
	ID                    uuid.UUID
	FirstName             string
	LastName              string
	Email                 string
	CreatedAt             pgtype.Timestamptz
	FarmName              string
	PostalCode            int32
	FieldCount            int64
	FieldAreaSquareMeters float64
	PlotCount             int64
	RentedPlotCount       int64
	PlotAreaSquareMeters  float64
	ActiveRentalCount     int64
	TotalCount            int64
}

// A farm is a farmer subtype row, not a table of its own, so "listing farms"
// means listing farmers from the farm side.
//
// The per-farm figures are computed with exactly the predicates
// statistics.sql uses -- same ST_Area over ::geography, same
// "period @> CURRENT_TIMESTAMP" test for rented right now. That is what makes
// these rows reconcile with GetPlatformStatistics: summing field_count,
// plot_count and rented_plot_count across every row of this list reproduces
// the platform figures exactly. Change a predicate in one place and the two
// admin screens start disagreeing.
// One page of the admin farm list.
//
// Each aggregate hangs off its own LATERAL join rather than a GROUP BY over a
// join of all three: grouping a farm's fields, plots and rentals in one pass
// would multiply the rows against each other and count each field once per
// plot. Separate laterals keep every figure independent of the others.
//
// An ungrouped aggregate returns one row even over no rows at all, so a farm
// with nothing is a row of zeros rather than a missing row -- the same promise
// GetFarmStatistics makes to a farmer who owns nothing. The COALESCEs restate
// that for sqlc, which types a LEFT JOIN's columns as nullable regardless.
// An empty search and a NULL postal code each mean "no filter", so one query
// serves every combination of them.
// Farm names are not unique, so id breaks the tie and keeps paging stable.
func (q *Queries) ListFarms(ctx context.Context, arg ListFarmsParams) ([]ListFarmsRow, error) {
	rows, err := q.db.Query(ctx, listFarms,
		arg.Search,
		arg.PostalCode,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFarmsRow
	for rows.Next() {
		var i ListFarmsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CreatedAt,
			&i.FarmName,
			&i.PostalCode,
			&i.FieldCount,
			&i.FieldAreaSquareMeters,
			&i.PlotCount,
			&i.RentedPlotCount,
			&i.PlotAreaSquareMeters,
			&i.ActiveRentalCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
