// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: field.sql

package database

import (
	"context"

	"github.com/google/uuid"
	geom "github.com/twpayne/go-geom"
)

const getFieldByID = `-- name: GetFieldByID :one
SELECT id, name, farmer, coordinates
FROM field
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFieldByID(ctx context.Context, id uuid.UUID) (Field, error) {
	row := q.db.QueryRow(ctx, getFieldByID, id)
	var i Field
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Farmer,
		&i.Coordinates,
	)
	return i, err
}

const getFieldOwner = `-- name: GetFieldOwner :one
SELECT farmer
FROM field
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFieldOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFieldOwner, id)
	var farmer uuid.UUID
	err := row.Scan(&farmer)
	return farmer, err
}

const getFieldsByFarmer = `-- name: GetFieldsByFarmer :many
SELECT id, name, farmer, coordinates
FROM field
WHERE farmer = $1
ORDER BY name
`

func (q *Queries) GetFieldsByFarmer(ctx context.Context, farmer uuid.UUID) ([]Field, error) {
	rows, err := q.db.Query(ctx, getFieldsByFarmer, farmer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Field
	for rows.Next() {
		var i Field
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Farmer,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertField = `-- name: InsertField :one
INSERT INTO field (name, farmer, coordinates) VALUES ($1, $2, $3) RETURNING id
`

type InsertFieldParams struct {
	Name        string
	Farmer      uuid.UUID
	Coordinates *geom.Polygon
}

func (q *Queries) InsertField(ctx context.Context, arg InsertFieldParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertField, arg.Name, arg.Farmer, arg.Coordinates)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
