// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field.sql

package database

import (
	"context"

	"github.com/google/uuid"
	geom "github.com/twpayne/go-geom"
)

const getFieldByID = `-- name: GetFieldByID :one
SELECT id, name, farm, coordinates
FROM field
WHERE id = $1
LIMIT 1
`

type GetFieldByIDRow struct {
	ID          uuid.UUID
	Name        string
	Farm        uuid.UUID
	Coordinates *geom.Polygon
}

func (q *Queries) GetFieldByID(ctx context.Context, id uuid.UUID) (GetFieldByIDRow, error) {
	row := q.db.QueryRow(ctx, getFieldByID, id)
	var i GetFieldByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Farm,
		&i.Coordinates,
	)
	return i, err
}

const getFieldFarm = `-- name: GetFieldFarm :one
SELECT farm
FROM field
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFieldFarm(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFieldFarm, id)
	var farm uuid.UUID
	err := row.Scan(&farm)
	return farm, err
}

const getFieldsByFarm = `-- name: GetFieldsByFarm :many
SELECT id, name, farm, coordinates
FROM field
WHERE farm = $1
ORDER BY name
`

type GetFieldsByFarmRow struct {
	ID          uuid.UUID
	Name        string
	Farm        uuid.UUID
	Coordinates *geom.Polygon
}

func (q *Queries) GetFieldsByFarm(ctx context.Context, farm uuid.UUID) ([]GetFieldsByFarmRow, error) {
	rows, err := q.db.Query(ctx, getFieldsByFarm, farm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFieldsByFarmRow
	for rows.Next() {
		var i GetFieldsByFarmRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Farm,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertField = `-- name: InsertField :one
INSERT INTO field (name, farm, coordinates) VALUES ($1, $2, $3) RETURNING id
`

type InsertFieldParams struct {
	Name        string
	Farm        uuid.UUID
	Coordinates *geom.Polygon
}

func (q *Queries) InsertField(ctx context.Context, arg InsertFieldParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertField, arg.Name, arg.Farm, arg.Coordinates)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
