// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	geom "github.com/twpayne/go-geom"
)

type Account struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Admin struct {
	AccountID uuid.UUID
	Role      int32
}

type Customer struct {
	AccountID  uuid.UUID
	PostalCode int32
}

type Farmer struct {
	AccountID  uuid.UUID
	FarmName   string
	PostalCode int32
}

type Field struct {
	ID          uuid.UUID
	Name        string
	Farmer      uuid.UUID
	Coordinates *geom.Polygon
}

type Plot struct {
	ID          uuid.UUID
	Name        string
	Field       uuid.UUID
	Coordinates *geom.Polygon
}
