// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	geom "github.com/twpayne/go-geom"
)

type Account struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Admin struct {
	AccountID uuid.UUID
	Role      int32
}

type Announcement struct {
	ID        uuid.UUID
	Farmer    uuid.UUID
	Subject   string
	Body      string
	CreatedAt pgtype.Timestamptz
}

type Crop struct {
	ID             uuid.UUID
	Name           string
	DurationMonths int32
}

type Customer struct {
	AccountID  uuid.UUID
	PostalCode int32
}

type Farmer struct {
	AccountID  uuid.UUID
	FarmName   string
	PostalCode int32
}

type Field struct {
	ID          uuid.UUID
	Name        string
	Farmer      uuid.UUID
	Coordinates *geom.Polygon
}

type Plot struct {
	ID          uuid.UUID
	Name        string
	Field       uuid.UUID
	Coordinates *geom.Polygon
}

type PlotCrop struct {
	Plot uuid.UUID
	Crop uuid.UUID
}

type PostalCode struct {
	ID          int32
	Zipcode     string
	Name        string
	Coordinates *geom.Point
}

type Rental struct {
	ID        uuid.UUID
	Plot      uuid.UUID
	Customer  uuid.UUID
	Period    pgtype.Range[pgtype.Timestamptz]
	CreatedAt pgtype.Timestamptz
	Crop      uuid.UUID
}
