// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_registration.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePendingRegistration = `-- name: DeletePendingRegistration :exec
DELETE FROM pending_registration WHERE id = $1
`

func (q *Queries) DeletePendingRegistration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingRegistration, id)
	return err
}

const getPendingRegistrationByID = `-- name: GetPendingRegistrationByID :one
SELECT id, first_name, last_name, email, password_hash, role,
       farm_name, address, description, postal_code
FROM pending_registration
WHERE id = $1 AND expires_at > CURRENT_TIMESTAMP
`

type GetPendingRegistrationByIDRow struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	Role         string
	FarmName     string
	Address      string
	Description  string
	PostalCode   int32
}

// Expiry is checked here, not by the caller, so "expired" and "never
// existed" collapse into the same pgx.ErrNoRows the repository already
// turns into ErrNotFound.
func (q *Queries) GetPendingRegistrationByID(ctx context.Context, id uuid.UUID) (GetPendingRegistrationByIDRow, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByID, id)
	var i GetPendingRegistrationByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FarmName,
		&i.Address,
		&i.Description,
		&i.PostalCode,
	)
	return i, err
}

const upsertPendingRegistration = `-- name: UpsertPendingRegistration :one
INSERT INTO pending_registration (
    first_name, last_name, email, password_hash, role,
    farm_name, address, description, postal_code, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (email) DO UPDATE SET
    first_name    = EXCLUDED.first_name,
    last_name     = EXCLUDED.last_name,
    password_hash = EXCLUDED.password_hash,
    role          = EXCLUDED.role,
    farm_name     = EXCLUDED.farm_name,
    address       = EXCLUDED.address,
    description   = EXCLUDED.description,
    postal_code   = EXCLUDED.postal_code,
    created_at    = CURRENT_TIMESTAMP,
    expires_at    = EXCLUDED.expires_at
RETURNING id
`

type UpsertPendingRegistrationParams struct {
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	Role         string
	FarmName     string
	Address      string
	Description  string
	PostalCode   int32
	ExpiresAt    pgtype.Timestamptz
}

// Re-registering the same email while a pending (unverified) registration
// exists refreshes it -- new data, new expiry, new id -- rather than
// erroring, so a user who lost the first email or mistyped a field is not
// stuck. A verified account's email is handled separately by the caller
// (GetAccountByEmail / ErrEmailTaken) before this is ever reached.
func (q *Queries) UpsertPendingRegistration(ctx context.Context, arg UpsertPendingRegistrationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPendingRegistration,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.FarmName,
		arg.Address,
		arg.Description,
		arg.PostalCode,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
