// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plot.sql

package database

import (
	"context"

	"github.com/google/uuid"
	geom "github.com/twpayne/go-geom"
)

const getNearestPlots = `-- name: GetNearestPlots :many
SELECT
    id,
    name,
    field,
    coordinates,
    ST_Distance(
        ST_Centroid(coordinates)::geography,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
    )::float8 AS distance_meters
FROM plot
WHERE NOT EXISTS (
    SELECT 1 FROM rental r
    WHERE r.plot = plot.id AND r.period @> CURRENT_TIMESTAMP
)
ORDER BY coordinates <-> ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)
LIMIT $3
`

type GetNearestPlotsParams struct {
	Lon         float64
	Lat         float64
	ResultLimit int32
}

type GetNearestPlotsRow struct {
	ID             uuid.UUID
	Name           string
	Field          uuid.UUID
	Coordinates    *geom.Polygon
	DistanceMeters float64
}

// Only plots that are free right now; a rental that has run out stops
// hiding its plot.
func (q *Queries) GetNearestPlots(ctx context.Context, arg GetNearestPlotsParams) ([]GetNearestPlotsRow, error) {
	rows, err := q.db.Query(ctx, getNearestPlots, arg.Lon, arg.Lat, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearestPlotsRow
	for rows.Next() {
		var i GetNearestPlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Field,
			&i.Coordinates,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlotByID = `-- name: GetPlotByID :one
SELECT id, name, field, coordinates
FROM plot
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlotByID(ctx context.Context, id uuid.UUID) (Plot, error) {
	row := q.db.QueryRow(ctx, getPlotByID, id)
	var i Plot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Field,
		&i.Coordinates,
	)
	return i, err
}

const getPlotField = `-- name: GetPlotField :one
SELECT field
FROM plot
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlotField(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPlotField, id)
	var field uuid.UUID
	err := row.Scan(&field)
	return field, err
}

const getPlotsByFields = `-- name: GetPlotsByFields :many
SELECT id, name, field, coordinates
FROM plot
WHERE field = ANY($1::uuid[])
ORDER BY name
`

func (q *Queries) GetPlotsByFields(ctx context.Context, dollar_1 []uuid.UUID) ([]Plot, error) {
	rows, err := q.db.Query(ctx, getPlotsByFields, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plot
	for rows.Next() {
		var i Plot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Field,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlot = `-- name: InsertPlot :one
INSERT INTO plot (name, field, coordinates) VALUES ($1, $2, $3) RETURNING id
`

type InsertPlotParams struct {
	Name        string
	Field       uuid.UUID
	Coordinates *geom.Polygon
}

func (q *Queries) InsertPlot(ctx context.Context, arg InsertPlotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlot, arg.Name, arg.Field, arg.Coordinates)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
