// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plot.sql

package database

import (
	"context"

	"github.com/google/uuid"
	geom "github.com/twpayne/go-geom"
)

const getPlotByID = `-- name: GetPlotByID :one
SELECT id, name, field, coordinates
FROM plot
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlotByID(ctx context.Context, id uuid.UUID) (Plot, error) {
	row := q.db.QueryRow(ctx, getPlotByID, id)
	var i Plot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Field,
		&i.Coordinates,
	)
	return i, err
}

const getPlotsByFields = `-- name: GetPlotsByFields :many
SELECT id, name, field, coordinates
FROM plot
WHERE field = ANY($1::uuid[])
ORDER BY name
`

func (q *Queries) GetPlotsByFields(ctx context.Context, dollar_1 []uuid.UUID) ([]Plot, error) {
	rows, err := q.db.Query(ctx, getPlotsByFields, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plot
	for rows.Next() {
		var i Plot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Field,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlot = `-- name: InsertPlot :one
INSERT INTO plot (name, field, coordinates) VALUES ($1, $2, $3) RETURNING id
`

type InsertPlotParams struct {
	Name        string
	Field       uuid.UUID
	Coordinates *geom.Polygon
}

func (q *Queries) InsertPlot(ctx context.Context, arg InsertPlotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPlot, arg.Name, arg.Field, arg.Coordinates)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
