// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plot.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	geom "github.com/twpayne/go-geom"
)

const getNearestPlots = `-- name: GetNearestPlots :many
SELECT
    plot.id,
    plot.name,
    plot.field,
    plot.coordinates,
    ST_Area(plot.coordinates::geography)::float8 AS area_square_meters,
    field.farm AS farm,
    ST_Distance(
        ST_Centroid(plot.coordinates)::geography,
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography
    )::float8 AS distance_meters
FROM plot
JOIN field ON field.id = plot.field
WHERE NOT EXISTS (
    SELECT 1 FROM rental r
    WHERE r.plot = plot.id AND r.period @> CURRENT_TIMESTAMP AND r.status <> 'declined'
)
AND ($3::uuid IS NULL OR field.farm = $3::uuid)
ORDER BY plot.coordinates <-> ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)
LIMIT $4
`

type GetNearestPlotsParams struct {
	Lon         float64
	Lat         float64
	Farm        *uuid.UUID
	ResultLimit int32
}

type GetNearestPlotsRow struct {
	ID               uuid.UUID
	Name             string
	Field            uuid.UUID
	Coordinates      *geom.Polygon
	AreaSquareMeters float64
	Farm             uuid.UUID
	DistanceMeters   float64
}

// Only plots that are free right now; a rental that has run out stops
// hiding its plot. A still-undecided request hides the plot too, same as
// the rental_no_overlap exclusion constraint -- only a declined request
// frees it.
// Optional: only this farm's plots (its detail page), instead of whichever
// farms happen to fill the nearest-N.
func (q *Queries) GetNearestPlots(ctx context.Context, arg GetNearestPlotsParams) ([]GetNearestPlotsRow, error) {
	rows, err := q.db.Query(ctx, getNearestPlots,
		arg.Lon,
		arg.Lat,
		arg.Farm,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearestPlotsRow
	for rows.Next() {
		var i GetNearestPlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Field,
			&i.Coordinates,
			&i.AreaSquareMeters,
			&i.Farm,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlotByID = `-- name: GetPlotByID :one
SELECT id, name, field, coordinates, base_price_cents_per_sqm_per_week, ST_Area(coordinates::geography)::float8 AS area_square_meters
FROM plot
WHERE id = $1
LIMIT 1
`

type GetPlotByIDRow struct {
	ID                          uuid.UUID
	Name                        string
	Field                       uuid.UUID
	Coordinates                 *geom.Polygon
	BasePriceCentsPerSqmPerWeek pgtype.Int4
	AreaSquareMeters            float64
}

func (q *Queries) GetPlotByID(ctx context.Context, id uuid.UUID) (GetPlotByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlotByID, id)
	var i GetPlotByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Field,
		&i.Coordinates,
		&i.BasePriceCentsPerSqmPerWeek,
		&i.AreaSquareMeters,
	)
	return i, err
}

const getPlotField = `-- name: GetPlotField :one
SELECT field
FROM plot
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlotField(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPlotField, id)
	var field uuid.UUID
	err := row.Scan(&field)
	return field, err
}

const getPlotsByFields = `-- name: GetPlotsByFields :many
SELECT id, name, field, coordinates, base_price_cents_per_sqm_per_week, ST_Area(coordinates::geography)::float8 AS area_square_meters
FROM plot
WHERE field = ANY($1::uuid[])
ORDER BY name
`

type GetPlotsByFieldsRow struct {
	ID                          uuid.UUID
	Name                        string
	Field                       uuid.UUID
	Coordinates                 *geom.Polygon
	BasePriceCentsPerSqmPerWeek pgtype.Int4
	AreaSquareMeters            float64
}

func (q *Queries) GetPlotsByFields(ctx context.Context, dollar_1 []uuid.UUID) ([]GetPlotsByFieldsRow, error) {
	rows, err := q.db.Query(ctx, getPlotsByFields, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlotsByFieldsRow
	for rows.Next() {
		var i GetPlotsByFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Field,
			&i.Coordinates,
			&i.BasePriceCentsPerSqmPerWeek,
			&i.AreaSquareMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlot = `-- name: InsertPlot :one
INSERT INTO plot (name, field, coordinates) VALUES ($1, $2, $3)
RETURNING id, ST_Area(coordinates::geography)::float8 AS area_square_meters
`

type InsertPlotParams struct {
	Name        string
	Field       uuid.UUID
	Coordinates *geom.Polygon
}

type InsertPlotRow struct {
	ID               uuid.UUID
	AreaSquareMeters float64
}

func (q *Queries) InsertPlot(ctx context.Context, arg InsertPlotParams) (InsertPlotRow, error) {
	row := q.db.QueryRow(ctx, insertPlot, arg.Name, arg.Field, arg.Coordinates)
	var i InsertPlotRow
	err := row.Scan(&i.ID, &i.AreaSquareMeters)
	return i, err
}

const updatePlotBasePrice = `-- name: UpdatePlotBasePrice :exec
UPDATE plot SET base_price_cents_per_sqm_per_week = $1 WHERE id = $2
`

type UpdatePlotBasePriceParams struct {
	BasePriceCentsPerSqmPerWeek pgtype.Int4
	ID                          uuid.UUID
}

func (q *Queries) UpdatePlotBasePrice(ctx context.Context, arg UpdatePlotBasePriceParams) error {
	_, err := q.db.Exec(ctx, updatePlotBasePrice, arg.BasePriceCentsPerSqmPerWeek, arg.ID)
	return err
}
