// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postal_code.sql

package database

import (
	"context"

	geom "github.com/twpayne/go-geom"
)

const findPostalCodeCoordinates = `-- name: FindPostalCodeCoordinates :one
SELECT coordinates
FROM postal_code
WHERE zipcode = $1
ORDER BY name
LIMIT 1
`

func (q *Queries) FindPostalCodeCoordinates(ctx context.Context, zipcode string) (*geom.Point, error) {
	row := q.db.QueryRow(ctx, findPostalCodeCoordinates, zipcode)
	var coordinates *geom.Point
	err := row.Scan(&coordinates)
	return coordinates, err
}

const findPostalCodeCoordinatesByCity = `-- name: FindPostalCodeCoordinatesByCity :one
SELECT coordinates
FROM postal_code
WHERE name ILIKE $1
ORDER BY name
LIMIT 1
`

func (q *Queries) FindPostalCodeCoordinatesByCity(ctx context.Context, name string) (*geom.Point, error) {
	row := q.db.QueryRow(ctx, findPostalCodeCoordinatesByCity, name)
	var coordinates *geom.Point
	err := row.Scan(&coordinates)
	return coordinates, err
}
