// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rental.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	geom "github.com/twpayne/go-geom"
)

const getRentalWithFieldByID = `-- name: GetRentalWithFieldByID :one
SELECT r.id, r.plot, r.customer, r.crop, r.status, p.field
FROM rental r
JOIN plot p ON p.id = r.plot
WHERE r.id = $1
`

type GetRentalWithFieldByIDRow struct {
	ID       uuid.UUID
	Plot     uuid.UUID
	Customer uuid.UUID
	Crop     uuid.UUID
	Status   string
	Field    uuid.UUID
}

// Fetches the rental together with the field its plot belongs to, so the
// service can check the deciding farmer owns that field before approving or
// declining.
func (q *Queries) GetRentalWithFieldByID(ctx context.Context, id uuid.UUID) (GetRentalWithFieldByIDRow, error) {
	row := q.db.QueryRow(ctx, getRentalWithFieldByID, id)
	var i GetRentalWithFieldByIDRow
	err := row.Scan(
		&i.ID,
		&i.Plot,
		&i.Customer,
		&i.Crop,
		&i.Status,
		&i.Field,
	)
	return i, err
}

const getRentalsByCustomer = `-- name: GetRentalsByCustomer :many
SELECT
    r.id,
    r.plot,
    r.customer,
    r.crop,
    lower(r.period)::timestamptz AS start_at,
    upper(r.period)::timestamptz AS end_at,
    r.status,
    r.message,
    r.decided_at,
    p.name AS plot_name,
    p.field,
    p.coordinates,
    ST_Area(p.coordinates::geography)::float8 AS plot_area_square_meters,
    c.name AS crop_name,
    c.duration_months AS crop_duration_months
FROM rental r
JOIN plot p ON p.id = r.plot
JOIN crop c ON c.id = r.crop
WHERE r.customer = $1
ORDER BY lower(r.period) DESC
`

type GetRentalsByCustomerRow struct {
	ID                   uuid.UUID
	Plot                 uuid.UUID
	Customer             uuid.UUID
	Crop                 uuid.UUID
	StartAt              pgtype.Timestamptz
	EndAt                pgtype.Timestamptz
	Status               string
	Message              string
	DecidedAt            pgtype.Timestamptz
	PlotName             string
	Field                uuid.UUID
	Coordinates          *geom.Polygon
	PlotAreaSquareMeters float64
	CropName             string
	CropDurationMonths   int32
}

func (q *Queries) GetRentalsByCustomer(ctx context.Context, customer uuid.UUID) ([]GetRentalsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, getRentalsByCustomer, customer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRentalsByCustomerRow
	for rows.Next() {
		var i GetRentalsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Plot,
			&i.Customer,
			&i.Crop,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.Message,
			&i.DecidedAt,
			&i.PlotName,
			&i.Field,
			&i.Coordinates,
			&i.PlotAreaSquareMeters,
			&i.CropName,
			&i.CropDurationMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRentalsByFarm = `-- name: GetRentalsByFarm :many
SELECT
    r.id,
    r.plot,
    r.customer,
    r.crop,
    lower(r.period)::timestamptz AS start_at,
    upper(r.period)::timestamptz AS end_at,
    r.status,
    r.message,
    r.decided_at,
    p.name AS plot_name,
    p.field,
    p.coordinates,
    ST_Area(p.coordinates::geography)::float8 AS plot_area_square_meters,
    f.name AS field_name,
    a.id AS customer_id,
    a.email AS customer_email,
    a.first_name AS customer_first_name,
    a.last_name AS customer_last_name
FROM rental r
JOIN plot p ON p.id = r.plot
JOIN field f ON f.id = p.field
JOIN account a ON a.id = r.customer
WHERE f.farm = $1
ORDER BY lower(r.period) DESC
`

type GetRentalsByFarmRow struct {
	ID                   uuid.UUID
	Plot                 uuid.UUID
	Customer             uuid.UUID
	Crop                 uuid.UUID
	StartAt              pgtype.Timestamptz
	EndAt                pgtype.Timestamptz
	Status               string
	Message              string
	DecidedAt            pgtype.Timestamptz
	PlotName             string
	Field                uuid.UUID
	Coordinates          *geom.Polygon
	PlotAreaSquareMeters float64
	FieldName            string
	CustomerID           uuid.UUID
	CustomerEmail        string
	CustomerFirstName    string
	CustomerLastName     string
}

// Every rental on the farm's own plots, active and historic alike: unlike
// GetCustomersOfFarmer, this is not restricted to r.period @> CURRENT_TIMESTAMP,
// since a farmer reviewing their rental history wants past bookings too.
func (q *Queries) GetRentalsByFarm(ctx context.Context, farm uuid.UUID) ([]GetRentalsByFarmRow, error) {
	rows, err := q.db.Query(ctx, getRentalsByFarm, farm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRentalsByFarmRow
	for rows.Next() {
		var i GetRentalsByFarmRow
		if err := rows.Scan(
			&i.ID,
			&i.Plot,
			&i.Customer,
			&i.Crop,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.Message,
			&i.DecidedAt,
			&i.PlotName,
			&i.Field,
			&i.Coordinates,
			&i.PlotAreaSquareMeters,
			&i.FieldName,
			&i.CustomerID,
			&i.CustomerEmail,
			&i.CustomerFirstName,
			&i.CustomerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRentalRequest = `-- name: InsertRentalRequest :one

INSERT INTO rental (plot, customer, crop, period, message)
VALUES (
    $1,
    $2,
    $3,
    tstzrange(
        $4::timestamptz,
        $4::timestamptz + make_interval(months => $5::int)
    ),
    $6
)
RETURNING id, status, lower(period)::timestamptz AS start_at, upper(period)::timestamptz AS end_at
`

type InsertRentalRequestParams struct {
	Plot           uuid.UUID
	Customer       uuid.UUID
	Crop           uuid.UUID
	StartAt        pgtype.Timestamptz
	DurationMonths int32
	Message        string
}

type InsertRentalRequestRow struct {
	ID      uuid.UUID
	Status  string
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
}

// The period column is never selected as a whole: sqlc maps tstzrange to a
// pgtype.Range, so the bounds are read out as plain timestamps instead.
func (q *Queries) InsertRentalRequest(ctx context.Context, arg InsertRentalRequestParams) (InsertRentalRequestRow, error) {
	row := q.db.QueryRow(ctx, insertRentalRequest,
		arg.Plot,
		arg.Customer,
		arg.Crop,
		arg.StartAt,
		arg.DurationMonths,
		arg.Message,
	)
	var i InsertRentalRequestRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
	)
	return i, err
}

const updateRentalStatus = `-- name: UpdateRentalStatus :one
UPDATE rental
SET status = $1, decided_at = CURRENT_TIMESTAMP
WHERE id = $2 AND status = 'requested'
RETURNING id, plot, customer, crop, status, lower(period)::timestamptz AS start_at, upper(period)::timestamptz AS end_at, message, decided_at
`

type UpdateRentalStatusParams struct {
	Status string
	ID     uuid.UUID
}

type UpdateRentalStatusRow struct {
	ID        uuid.UUID
	Plot      uuid.UUID
	Customer  uuid.UUID
	Crop      uuid.UUID
	Status    string
	StartAt   pgtype.Timestamptz
	EndAt     pgtype.Timestamptz
	Message   string
	DecidedAt pgtype.Timestamptz
}

// Only a still-requested rental can be decided: the WHERE guard makes this
// idempotent-safe, since a second approve/decline on the same row returns no
// rows instead of silently overwriting an earlier decision.
func (q *Queries) UpdateRentalStatus(ctx context.Context, arg UpdateRentalStatusParams) (UpdateRentalStatusRow, error) {
	row := q.db.QueryRow(ctx, updateRentalStatus, arg.Status, arg.ID)
	var i UpdateRentalStatusRow
	err := row.Scan(
		&i.ID,
		&i.Plot,
		&i.Customer,
		&i.Crop,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.Message,
		&i.DecidedAt,
	)
	return i, err
}
