// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rental_checkout.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeRentalCheckout = `-- name: CompleteRentalCheckout :one
UPDATE rental_checkout
SET status = 'completed', rental = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND status = 'pending'
RETURNING id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
`

type CompleteRentalCheckoutParams struct {
	Rental *uuid.UUID
	ID     uuid.UUID
}

// The WHERE guard makes this idempotent-safe: Stripe retries webhook
// delivery, so a second checkout.session.completed for the same session
// must not re-run this and must not overwrite which rental it produced.
func (q *Queries) CompleteRentalCheckout(ctx context.Context, arg CompleteRentalCheckoutParams) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, completeRentalCheckout, arg.Rental, arg.ID)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireRentalCheckout = `-- name: ExpireRentalCheckout :one
UPDATE rental_checkout
SET status = 'expired', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
RETURNING id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
`

// Same idempotency guard as CompleteRentalCheckout.
func (q *Queries) ExpireRentalCheckout(ctx context.Context, id uuid.UUID) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, expireRentalCheckout, id)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failRentalCheckout = `-- name: FailRentalCheckout :one
UPDATE rental_checkout
SET status = 'failed', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'pending'
RETURNING id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
`

// Same idempotency guard as CompleteRentalCheckout.
func (q *Queries) FailRentalCheckout(ctx context.Context, id uuid.UUID) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, failRentalCheckout, id)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompletedRentalCheckoutByRental = `-- name: GetCompletedRentalCheckoutByRental :one
SELECT id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
FROM rental_checkout
WHERE rental = $1 AND status = 'completed'
LIMIT 1
`

// Used when a farmer declines a rental, to find the payment that must now
// be refunded. Returns no rows (mapped to ErrNotFound) if the rental was
// never paid for through Stripe.
func (q *Queries) GetCompletedRentalCheckoutByRental(ctx context.Context, rental *uuid.UUID) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, getCompletedRentalCheckoutByRental, rental)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRentalCheckoutBySessionID = `-- name: GetRentalCheckoutBySessionID :one
SELECT id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
FROM rental_checkout
WHERE stripe_checkout_session_id = $1
LIMIT 1
`

func (q *Queries) GetRentalCheckoutBySessionID(ctx context.Context, stripeCheckoutSessionID string) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, getRentalCheckoutBySessionID, stripeCheckoutSessionID)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRentalCheckout = `-- name: InsertRentalCheckout :one
INSERT INTO rental_checkout (customer, plot, crop, start_at, message, stripe_checkout_session_id, amount_cents)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
`

type InsertRentalCheckoutParams struct {
	Customer                uuid.UUID
	Plot                    uuid.UUID
	Crop                    uuid.UUID
	StartAt                 pgtype.Timestamptz
	Message                 string
	StripeCheckoutSessionID string
	AmountCents             int32
}

func (q *Queries) InsertRentalCheckout(ctx context.Context, arg InsertRentalCheckoutParams) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, insertRentalCheckout,
		arg.Customer,
		arg.Plot,
		arg.Crop,
		arg.StartAt,
		arg.Message,
		arg.StripeCheckoutSessionID,
		arg.AmountCents,
	)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRentalCheckoutRefunded = `-- name: MarkRentalCheckoutRefunded :one
UPDATE rental_checkout
SET status = 'refunded', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'completed'
RETURNING id, customer, plot, crop, start_at, message, stripe_checkout_session_id, status, amount_cents, rental, created_at, updated_at
`

// Same idempotency guard as CompleteRentalCheckout.
func (q *Queries) MarkRentalCheckoutRefunded(ctx context.Context, id uuid.UUID) (RentalCheckout, error) {
	row := q.db.QueryRow(ctx, markRentalCheckoutRefunded, id)
	var i RentalCheckout
	err := row.Scan(
		&i.ID,
		&i.Customer,
		&i.Plot,
		&i.Crop,
		&i.StartAt,
		&i.Message,
		&i.StripeCheckoutSessionID,
		&i.Status,
		&i.AmountCents,
		&i.Rental,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
