// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rental.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	geom "github.com/twpayne/go-geom"
)

const getRentalsByCustomer = `-- name: GetRentalsByCustomer :many
SELECT
    r.id,
    r.plot,
    r.customer,
    r.crop,
    lower(r.period)::timestamptz AS start_at,
    upper(r.period)::timestamptz AS end_at,
    p.name AS plot_name,
    p.field,
    p.coordinates,
    c.name AS crop_name,
    c.duration_months AS crop_duration_months
FROM rental r
JOIN plot p ON p.id = r.plot
JOIN crop c ON c.id = r.crop
WHERE r.customer = $1
ORDER BY lower(r.period) DESC
`

type GetRentalsByCustomerRow struct {
	ID                 uuid.UUID
	Plot               uuid.UUID
	Customer           uuid.UUID
	Crop               uuid.UUID
	StartAt            pgtype.Timestamptz
	EndAt              pgtype.Timestamptz
	PlotName           string
	Field              uuid.UUID
	Coordinates        *geom.Polygon
	CropName           string
	CropDurationMonths int32
}

func (q *Queries) GetRentalsByCustomer(ctx context.Context, customer uuid.UUID) ([]GetRentalsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, getRentalsByCustomer, customer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRentalsByCustomerRow
	for rows.Next() {
		var i GetRentalsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Plot,
			&i.Customer,
			&i.Crop,
			&i.StartAt,
			&i.EndAt,
			&i.PlotName,
			&i.Field,
			&i.Coordinates,
			&i.CropName,
			&i.CropDurationMonths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRental = `-- name: InsertRental :one


INSERT INTO rental (plot, customer, crop, period)
VALUES (
    $1,
    $2,
    $3,
    tstzrange(
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP + make_interval(months => $4::int)
    )
)
RETURNING id, lower(period)::timestamptz AS start_at, upper(period)::timestamptz AS end_at
`

type InsertRentalParams struct {
	Plot           uuid.UUID
	Customer       uuid.UUID
	Crop           uuid.UUID
	DurationMonths int32
}

type InsertRentalRow struct {
	ID      uuid.UUID
	StartAt pgtype.Timestamptz
	EndAt   pgtype.Timestamptz
}

// The period column is never selected as a whole: sqlc maps tstzrange to a
// pgtype.Range, so the bounds are read out as plain timestamps instead.
// The period starts at the database's clock rather than one supplied by the
// caller: the availability filter compares against CURRENT_TIMESTAMP, so a
// start time from a host whose clock runs ahead would leave the plot looking
// available for the difference.
func (q *Queries) InsertRental(ctx context.Context, arg InsertRentalParams) (InsertRentalRow, error) {
	row := q.db.QueryRow(ctx, insertRental,
		arg.Plot,
		arg.Customer,
		arg.Crop,
		arg.DurationMonths,
	)
	var i InsertRentalRow
	err := row.Scan(&i.ID, &i.StartAt, &i.EndAt)
	return i, err
}
