// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season_crop.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCropSeasonRule = `-- name: DeleteCropSeasonRule :execrows
DELETE FROM season_crop WHERE id = $1
`

func (q *Queries) DeleteCropSeasonRule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCropSeasonRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCropSeasonRuleByID = `-- name: GetCropSeasonRuleByID :one
SELECT id, season_id, crop_id, farm_id, created_at, updated_at
FROM season_crop WHERE id = $1
`

func (q *Queries) GetCropSeasonRuleByID(ctx context.Context, id uuid.UUID) (SeasonCrop, error) {
	row := q.db.QueryRow(ctx, getCropSeasonRuleByID, id)
	var i SeasonCrop
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.CropID,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCropSeasonRuleForCrop = `-- name: GetCropSeasonRuleForCrop :one
SELECT id, season_id, crop_id, farm_id, created_at, updated_at
FROM season_crop
WHERE crop_id = $1 AND farm_id IS NOT DISTINCT FROM $2
`

type GetCropSeasonRuleForCropParams struct {
	Crop uuid.UUID
	Farm *uuid.UUID
}

// The rule for this crop in exactly one set: the default rule when farm is
// NULL, that farm's own rule otherwise. Unlike GetEffectiveSeasonForCrop,
// this never falls back from a farm's set to the defaults - it is how a
// write finds the exact row it is repointing or removing.
func (q *Queries) GetCropSeasonRuleForCrop(ctx context.Context, arg GetCropSeasonRuleForCropParams) (SeasonCrop, error) {
	row := q.db.QueryRow(ctx, getCropSeasonRuleForCrop, arg.Crop, arg.Farm)
	var i SeasonCrop
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.CropID,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEffectiveSeasonForCrop = `-- name: GetEffectiveSeasonForCrop :one
SELECT s.id, s.farm, s.name, s.start_month, s.start_day, s.end_month, s.end_day, s.created_at, s.updated_at
FROM season_crop sc
JOIN season s ON s.id = sc.season_id
WHERE sc.crop_id = $1 AND sc.farm_id = $2
UNION ALL
SELECT s.id, s.farm, s.name, s.start_month, s.start_day, s.end_month, s.end_day, s.created_at, s.updated_at
FROM season_crop sc
JOIN season s ON s.id = sc.season_id
WHERE sc.crop_id = $1 AND sc.farm_id IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM season_crop other WHERE other.crop_id = $1 AND other.farm_id = $2
  )
LIMIT 1
`

type GetEffectiveSeasonForCropParams struct {
	Crop uuid.UUID
	Farm *uuid.UUID
}

// The season a crop is checked against for a given farm: that farm's own
// rule if it has one, the default rule otherwise. Returns no rows if
// neither exists, meaning the crop is unrestricted for that farm.
func (q *Queries) GetEffectiveSeasonForCrop(ctx context.Context, arg GetEffectiveSeasonForCropParams) (Season, error) {
	row := q.db.QueryRow(ctx, getEffectiveSeasonForCrop, arg.Crop, arg.Farm)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Farm,
		&i.Name,
		&i.StartMonth,
		&i.StartDay,
		&i.EndMonth,
		&i.EndDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEffectiveSeasonsForCrops = `-- name: GetEffectiveSeasonsForCrops :many
SELECT
    pair.crop::uuid AS for_crop,
    pair.farm::uuid AS for_farm,
    s.id, s.farm, s.name, s.start_month, s.start_day, s.end_month, s.end_day, s.created_at, s.updated_at
FROM (
    SELECT unnest($1::uuid[]) AS crop, unnest($2::uuid[]) AS farm
) AS pair
JOIN season_crop sc ON sc.crop_id = pair.crop
    AND sc.farm_id IS NOT DISTINCT FROM (
        SELECT farm_id FROM season_crop WHERE crop_id = pair.crop AND farm_id = pair.farm
        UNION ALL
        SELECT NULL WHERE NOT EXISTS (
            SELECT 1 FROM season_crop WHERE crop_id = pair.crop AND farm_id = pair.farm
        )
        LIMIT 1
    )
JOIN season s ON s.id = sc.season_id
`

type GetEffectiveSeasonsForCropsParams struct {
	Crops []uuid.UUID
	Farms []uuid.UUID
}

type GetEffectiveSeasonsForCropsRow struct {
	ForCrop    uuid.UUID
	ForFarm    uuid.UUID
	ID         uuid.UUID
	Farm       *uuid.UUID
	Name       string
	StartMonth int16
	StartDay   int16
	EndMonth   int16
	EndDay     int16
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// The batched form of GetEffectiveSeasonForCrop: the season each (crop,
// farm) pair is checked against, in one round trip - a plot listing with
// several crops reads all of them at once instead of once per crop. A pair
// with no rule at all, default or farm-owned, is absent from the result
// rather than a row with nulls.
func (q *Queries) GetEffectiveSeasonsForCrops(ctx context.Context, arg GetEffectiveSeasonsForCropsParams) ([]GetEffectiveSeasonsForCropsRow, error) {
	rows, err := q.db.Query(ctx, getEffectiveSeasonsForCrops, arg.Crops, arg.Farms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEffectiveSeasonsForCropsRow
	for rows.Next() {
		var i GetEffectiveSeasonsForCropsRow
		if err := rows.Scan(
			&i.ForCrop,
			&i.ForFarm,
			&i.ID,
			&i.Farm,
			&i.Name,
			&i.StartMonth,
			&i.StartDay,
			&i.EndMonth,
			&i.EndDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCropSeasonRule = `-- name: InsertCropSeasonRule :one
INSERT INTO season_crop (season_id, crop_id, farm_id)
VALUES ($1, $2, $3)
RETURNING id, season_id, crop_id, farm_id, created_at, updated_at
`

type InsertCropSeasonRuleParams struct {
	SeasonID uuid.UUID
	CropID   uuid.UUID
	FarmID   *uuid.UUID
}

// farm is NULL for the default rule, or a farm id for that farm's own.
// season must belong to that same farm (or be a default, for a default
// rule) - the caller validates this before inserting, since a plain FK
// cannot express it.
func (q *Queries) InsertCropSeasonRule(ctx context.Context, arg InsertCropSeasonRuleParams) (SeasonCrop, error) {
	row := q.db.QueryRow(ctx, insertCropSeasonRule, arg.SeasonID, arg.CropID, arg.FarmID)
	var i SeasonCrop
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.CropID,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCropSeasonRule = `-- name: UpdateCropSeasonRule :one
UPDATE season_crop
SET season_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, season_id, crop_id, farm_id, created_at, updated_at
`

type UpdateCropSeasonRuleParams struct {
	SeasonID uuid.UUID
	ID       uuid.UUID
}

// Only the season a rule points at can change; the crop and farm it belongs
// to are fixed at creation.
func (q *Queries) UpdateCropSeasonRule(ctx context.Context, arg UpdateCropSeasonRuleParams) (SeasonCrop, error) {
	row := q.db.QueryRow(ctx, updateCropSeasonRule, arg.SeasonID, arg.ID)
	var i SeasonCrop
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.CropID,
		&i.FarmID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
