// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteSeason = `-- name: DeleteSeason :execrows
DELETE FROM season WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeason, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultSeasons = `-- name: GetDefaultSeasons :many
SELECT id, farm, name, start_month, start_day, end_month, end_day, created_at, updated_at
FROM season WHERE farm IS NULL ORDER BY start_month, start_day
`

func (q *Queries) GetDefaultSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, getDefaultSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Farm,
			&i.Name,
			&i.StartMonth,
			&i.StartDay,
			&i.EndMonth,
			&i.EndDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFarmSeasons = `-- name: GetFarmSeasons :many
SELECT id, farm, name, start_month, start_day, end_month, end_day, created_at, updated_at
FROM season WHERE farm = $1 ORDER BY start_month, start_day
`

func (q *Queries) GetFarmSeasons(ctx context.Context, farm *uuid.UUID) ([]Season, error) {
	rows, err := q.db.Query(ctx, getFarmSeasons, farm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Farm,
			&i.Name,
			&i.StartMonth,
			&i.StartDay,
			&i.EndMonth,
			&i.EndDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, farm, name, start_month, start_day, end_month, end_day, created_at, updated_at
FROM season WHERE id = $1
`

func (q *Queries) GetSeasonByID(ctx context.Context, id uuid.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Farm,
		&i.Name,
		&i.StartMonth,
		&i.StartDay,
		&i.EndMonth,
		&i.EndDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSeason = `-- name: InsertSeason :one
INSERT INTO season (farm, name, start_month, start_day, end_month, end_day)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, farm, name, start_month, start_day, end_month, end_day, created_at, updated_at
`

type InsertSeasonParams struct {
	Farm       *uuid.UUID
	Name       string
	StartMonth int16
	StartDay   int16
	EndMonth   int16
	EndDay     int16
}

// farm is NULL for a default season, or a farm id for that farm's own.
func (q *Queries) InsertSeason(ctx context.Context, arg InsertSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, insertSeason,
		arg.Farm,
		arg.Name,
		arg.StartMonth,
		arg.StartDay,
		arg.EndMonth,
		arg.EndDay,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Farm,
		&i.Name,
		&i.StartMonth,
		&i.StartDay,
		&i.EndMonth,
		&i.EndDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE season
SET name = $1, start_month = $2, start_day = $3,
    end_month = $4, end_day = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, farm, name, start_month, start_day, end_month, end_day, created_at, updated_at
`

type UpdateSeasonParams struct {
	Name       string
	StartMonth int16
	StartDay   int16
	EndMonth   int16
	EndDay     int16
	ID         uuid.UUID
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeason,
		arg.Name,
		arg.StartMonth,
		arg.StartDay,
		arg.EndMonth,
		arg.EndDay,
		arg.ID,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Farm,
		&i.Name,
		&i.StartMonth,
		&i.StartDay,
		&i.EndMonth,
		&i.EndDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
