// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_plan.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSubscriptionPlans = `-- name: GetActiveSubscriptionPlans :many
SELECT id, code, display_name, max_plots, price_cents, stripe_price_id, is_active, created_at, updated_at
FROM subscription_plan
WHERE is_active
ORDER BY price_cents
`

func (q *Queries) GetActiveSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, getActiveSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DisplayName,
			&i.MaxPlots,
			&i.PriceCents,
			&i.StripePriceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionPlanByCode = `-- name: GetSubscriptionPlanByCode :one
SELECT id, code, display_name, max_plots, price_cents, stripe_price_id, is_active, created_at, updated_at
FROM subscription_plan
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionPlanByCode(ctx context.Context, code string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByCode, code)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.MaxPlots,
		&i.PriceCents,
		&i.StripePriceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionPlanByID = `-- name: GetSubscriptionPlanByID :one
SELECT id, code, display_name, max_plots, price_cents, stripe_price_id, is_active, created_at, updated_at
FROM subscription_plan
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionPlanByID(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.MaxPlots,
		&i.PriceCents,
		&i.StripePriceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSubscriptionPlan = `-- name: InsertSubscriptionPlan :exec
INSERT INTO subscription_plan (code, display_name, max_plots, price_cents, stripe_price_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertSubscriptionPlanParams struct {
	Code          string
	DisplayName   string
	MaxPlots      pgtype.Int4
	PriceCents    int32
	StripePriceID string
}

// Used only at startup to seed the three fixed tiers -- see
// seedSubscriptionPlans in main.go.
func (q *Queries) InsertSubscriptionPlan(ctx context.Context, arg InsertSubscriptionPlanParams) error {
	_, err := q.db.Exec(ctx, insertSubscriptionPlan,
		arg.Code,
		arg.DisplayName,
		arg.MaxPlots,
		arg.PriceCents,
		arg.StripePriceID,
	)
	return err
}

const listSubscriptionPlans = `-- name: ListSubscriptionPlans :many
SELECT id, code, display_name, max_plots, price_cents, stripe_price_id, is_active, created_at, updated_at
FROM subscription_plan
ORDER BY price_cents
`

// The admin view: every plan, active or retired.
func (q *Queries) ListSubscriptionPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPlan
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DisplayName,
			&i.MaxPlots,
			&i.PriceCents,
			&i.StripePriceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriptionPlanActive = `-- name: SetSubscriptionPlanActive :exec
UPDATE subscription_plan
SET is_active = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type SetSubscriptionPlanActiveParams struct {
	IsActive bool
	ID       uuid.UUID
}

func (q *Queries) SetSubscriptionPlanActive(ctx context.Context, arg SetSubscriptionPlanActiveParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionPlanActive, arg.IsActive, arg.ID)
	return err
}

const updateSubscriptionPlanPrice = `-- name: UpdateSubscriptionPlanPrice :one
UPDATE subscription_plan
SET price_cents = $1, stripe_price_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, code, display_name, max_plots, price_cents, stripe_price_id, is_active, created_at, updated_at
`

type UpdateSubscriptionPlanPriceParams struct {
	PriceCents    int32
	StripePriceID string
	ID            uuid.UUID
}

// Repoints a plan at a newly created Stripe Price -- see subscription_plan's
// doc comment for why this is a new Stripe Price rather than an update to
// the existing one. Only affects future subscriptions to this plan;
// existing farmer_subscription rows keep referencing whatever Stripe
// Subscription (and thus Price) they were created against.
func (q *Queries) UpdateSubscriptionPlanPrice(ctx context.Context, arg UpdateSubscriptionPlanPriceParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlanPrice, arg.PriceCents, arg.StripePriceID, arg.ID)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.MaxPlots,
		&i.PriceCents,
		&i.StripePriceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
